"""add_asset_tables

Revision ID: ee72898df6cc
Revises: 
Create Date: 2026-03-17 10:16:29.811643
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee72898df6cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_internet_facing', sa.Boolean(), nullable=True),
    sa.Column('network_zone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_software_obs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=False),
    sa.Column('product', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('cpe', sa.String(length=256), nullable=True),
    sa.Column('purl', sa.String(length=512), nullable=True),
    sa.Column('install_path', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_sw_asset', 'asset_software_obs', ['asset_id'], unique=False)
    op.create_index('ix_asset_sw_product', 'asset_software_obs', ['vendor', 'product'], unique=False)
    op.create_table('control_obs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=True),
    sa.Column('control_type', sa.String(length=64), nullable=False),
    sa.Column('control_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effectiveness', sa.Float(), nullable=True),
    sa.Column('evidence_detail', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerability.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_control_asset', 'control_obs', ['asset_id'], unique=False)
    op.create_table('decision_obs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_chain_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_name', sa.String(length=64), nullable=True),
    sa.Column('policy_version', sa.String(length=16), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(), nullable=True),
    sa.Column('overridden_by', sa.String(length=128), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerability.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_action', 'decision_obs', ['action'], unique=False)
    op.create_index('ix_decision_asset_vuln', 'decision_obs', ['asset_id', 'vulnerability_id'], unique=False)
    op.create_table('reachability_obs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=False),
    sa.Column('reachability_type', sa.String(length=32), nullable=False),
    sa.Column('is_reachable', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_detail', sa.Text(), nullable=True),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerability.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reach_asset_vuln', 'reachability_obs', ['asset_id', 'vulnerability_id'], unique=False)
    op.create_table('validation_obs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=False),
    sa.Column('validation_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=True),
    sa.Column('evidence_detail', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerability.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_asset_vuln', 'validation_obs', ['asset_id', 'vulnerability_id'], unique=False)
    op.create_table('vex_statement_obs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vulnerability_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=False),
    sa.Column('product', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('impact_statement', sa.Text(), nullable=True),
    sa.Column('action_statement', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerability.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vex_asset', 'vex_statement_obs', ['asset_id'], unique=False)
    op.create_index('ix_vex_product', 'vex_statement_obs', ['vendor', 'product'], unique=False)
    op.create_index('ix_vex_vuln', 'vex_statement_obs', ['vulnerability_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vex_vuln', table_name='vex_statement_obs')
    op.drop_index('ix_vex_product', table_name='vex_statement_obs')
    op.drop_index('ix_vex_asset', table_name='vex_statement_obs')
    op.drop_table('vex_statement_obs')
    op.drop_index('ix_validation_asset_vuln', table_name='validation_obs')
    op.drop_table('validation_obs')
    op.drop_index('ix_reach_asset_vuln', table_name='reachability_obs')
    op.drop_table('reachability_obs')
    op.drop_index('ix_decision_asset_vuln', table_name='decision_obs')
    op.drop_index('ix_decision_action', table_name='decision_obs')
    op.drop_table('decision_obs')
    op.drop_index('ix_control_asset', table_name='control_obs')
    op.drop_table('control_obs')
    op.drop_index('ix_asset_sw_product', table_name='asset_software_obs')
    op.drop_index('ix_asset_sw_asset', table_name='asset_software_obs')
    op.drop_table('asset_software_obs')
    op.drop_table('asset')
    # ### end Alembic commands ###
